export const SET_USER = 'SET_USER';
export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_EXPENSE = 'SET_EXPENSE';
export const RECEIVE_PRICE_SUCESS = 'RECEIVE_PRICE_SUCESS';
export const RECEIVE_PRICE_FAILURE = 'RECEIVE_PRICE_FAILURE';
